name: Issue Triggered Workflow

on:
  issues:
    types: [opened]

jobs:
  issue_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Issue Details
        run: |
          echo "Issue Title: \"${{ github.event.issue.title }}\""
          echo "Issue Body: \"${{ github.event.issue.body }}\""
          echo "Issue URL: \"${{ github.event.issue.html_url }}\""
